// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWm90SFzI1FUtMoMC_mnXpXmtzgamySxo',
    appId: '1:832923323749:web:7240fc9a7e7da2ae17658c',
    messagingSenderId: '832923323749',
    projectId: 'glaze-production',
    authDomain: 'glaze-production.firebaseapp.com',
    storageBucket: 'glaze-production.firebasestorage.app',
    measurementId: 'G-V6LWB79J93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABz0aBD7YxH7M44AolxwE46gL1PIYtvcM',
    appId: '1:832923323749:android:cb0add44f156e2d817658c',
    messagingSenderId: '832923323749',
    projectId: 'glaze-production',
    storageBucket: 'glaze-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPn8_ygN1qBvI-EwRfBgHWubtPd4QmbJI',
    appId: '1:832923323749:ios:a414e158a297384817658c',
    messagingSenderId: '832923323749',
    projectId: 'glaze-production',
    storageBucket: 'glaze-production.firebasestorage.app',
    iosBundleId: 'com.glaze.glazeApp',
  );
}
