name: glaze
version: 1.0.0+17

publish_to: none
environment:
  sdk: ^3.5.2
description: A new Flutter project.
dependencies:
  app_links: 6.1.3
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  glass_kit: ^4.0.1
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  lucide_icons_flutter: ^2.0.6
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  preload_page_view: ^0.2.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4
  video_compress: ^3.1.4
  video_player: ^2.9.3
dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.8.2
  json_serializable: ^6.9.0
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.6.3
flutter_gen:
  output: lib/gen
  line_length: 80
  integrations:
    image: true
    flutter_svg: true
    lottie: true
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/lotties/
    - assets/others/
  fonts:
    - family: Hit and Run
      fonts:
        - asset: assets/fonts/HitandRun-Regular.ttf
          style: normal
          weight: 400
    - family: Roboto Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Roboto Italic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: Roboto SemiBold
      fonts:
        - asset: assets/fonts/Roboto-SemiBold.ttf
