// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqRVqLvNTLx5-iSVKmh9G__fnPEW49lL8',
    appId: '1:427955485240:web:c54303dd7d76ba4720c4cd',
    messagingSenderId: '427955485240',
    projectId: 'glaze-development',
    authDomain: 'glaze-development.firebaseapp.com',
    storageBucket: 'glaze-development.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqpiZQ92lDbHD3xKxxMscApIM0LaQSWJc',
    appId: '1:427955485240:android:04ec61e7e8fa391120c4cd',
    messagingSenderId: '427955485240',
    projectId: 'glaze-development',
    storageBucket: 'glaze-development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntlFRyhL6vSy-AnJv6yo_-J2ERK5uOJc',
    appId: '1:427955485240:ios:284ecac4b5deb14820c4cd',
    messagingSenderId: '427955485240',
    projectId: 'glaze-development',
    storageBucket: 'glaze-development.firebasestorage.app',
    iosBundleId: 'com.glaze.glazeApp.development',
  );
}
